services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:mc7cMSKpYr5UpNcy@nlnppwumehcddtkcbqck.supabase.co:5432/postgres"
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
