version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/inventory
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

Run the following command to start the services: "docker-compose up --build"
